name: Update mirror
on:
  workflow_dispatch:

jobs:
  update_mirror:
    name: Update mirror
    runs-on: [ubuntu-latest]
    permissions:
      contents: write

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: Checkout the source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: mirror

    - name: Pull commits
      run: |
        git remote add source https://skia.googlesource.com/skcms
        git fetch source
        git branch --set-upstream-to=source/main mirror
        NEW_COMMITS=false
        HERE=$(git rev-parse @)
        THERE=$(git rev-parse source)
        if [ $HERE = $THERE ]; then
          echo "::notice title::Everything is up-to-date"
        else
          echo "::notice title::Pulling new commits"
          git pull
          NEW_COMMITS=true
        fi
        echo "NEW_COMMITS=${NEW_COMMITS}" >> $GITHUB_ENV

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: env.NEW_COMMITS == 'true'
      run: |
        git push https://oauth2:${GITHUB_TOKEN}@github.com/google/skcms.git mirror --force
